const CONSTANTS = {
    LOADING: "REQUEST_DATA",
    LOAD_SUCCESS: "RECEIVE_DATA",
    SET_CREATOR_NAME: "SET_CREATOR_NAME",
    SET_COMMENT: "SET_COMMENT",
    RESET_FORM: "RESET_FORM" 
};

export default CONSTANTS;
