const CONSTANTS = {
    SET_CREATOR_NAME: "SET_CREATOR_NAME",
    SET_COMMENT: "SET_COMMENT",
    SET_NEW_ROW: "SET_NEW_ROW",
    SET_PRICE: "SET_PRICE",
    SET_QUANTITY: "SET_QUANTITY",
    RESET_FORM: "RESET_FORM",    
};

export default CONSTANTS;
